version: 2.1

orbs:
  prodsec: vulnmap/prodsec-orb@1.0
  vulnmap: vulnmap/vulnmap@1

jobs:
  # All Vulnmap scanning jobs use a VULNMAP_TOKEN from the tiki-vulnmap Circle context,
  # which correponds to the tiki-vulnmap-circle-context service account in
  # https://app.vulnmap.khulnasoft.com/org/cloud-cloud/manage/service-accounts
  # It's not in 1password, just rotate it and configure it in Circle directly if
  # needed.
  scan-code:
    resource_class: medium
    docker:
      - image: cimg/go:1.20
    steps:
      - checkout
      - vulnmap/scan:
          organization: cloud-cloud
          command: code test
          fail-on-issues: true
          severity-threshold: high
          monitor-on-build: false

  scan-deps:
    resource_class: medium
    docker:
      - image: cimg/go:1.20
    steps:
      - checkout
      - vulnmap/scan:
          organization: cloud-cloud
          additional-arguments: --all-projects
          fail-on-issues: true
          severity-threshold: high
          monitor-on-build: false

workflows:
  version: 2
  CICD:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - vulnmap-bot-slack
          channel: group-cloud-security-vulnerabilities-alerts

      - scan-code:
          name: Scan Code
          context:
            - tiki-vulnmap

      - scan-deps:
          name: Scan Dependencies
          context:
            - tiki-vulnmap
